<html>

<?php 

echo "Text generated by <b> PHP </b>"; #Bold font
echo "<br>";
echo "Text generated by <i> PHP </i>"; #Italics font
echo "<br>";
echo "Text generated by <u> PHP </u>"; #Underline Text

?>

</html>
